<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/sathish4fri/classictheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Sathish Kumar , Liang Lee
 * @copyright All right reserved Sathish kumar 2014.
 * @ide The Code is Generated by Sathish kumar php IDE.
 */
$english = array(	
	'ohyes:home' => "Home",	
	'ohyes:photos' => 'Photos',
	'ohyes:blog' => 'Blog',
	'ohyes:bookmarks' => 'Bookmarks',
	'ohyes:file' => 'File',
	'ohyes:pages' => 'Pages',
	'ohyes:messages' => 'Messages',
	'ohyes:groups' => 'Groups',
	
	'ohyes:admin:menu' => 'Admin Menu',
	'ohyes:add:friend' => 'Add Friend',
	'ohyes:un:friend' => 'Unfriend',
	'ohyes:message' => 'Message',
	'ohyes:about' => 'About',
	'profile:edit' => 'Edit',
	
	'ohyes:cover:add' => 'Add Cover',
	'ohyes:theme:cover:done' => 'Cover is added',
	'ohyes:theme:cover:no' => 'Cannot add cover',
	'ohyes:theme:cover:removed' => 'Cover has been removed',
	'ohyes:theme:cover:remove:error' => 'Cannot remove cover, please try again',
	
 );
					
add_translation("en", $english);
