<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 

class ClassicTheme {
/**
* Set cover settings;
* @access system
* @return return;
*/

public function isCoverSet($params = array()){
return elgg_set_plugin_user_setting(
         $params['name'], 
		 $params['value'] ,
		 $params['user_guid'], 
		 $params['plugin_id']
		 );
}
/**
* Unlink Profile Cover;
* @access system
* @return return;
*/
public function UnlinkCover($user){
$this->iscoversettings = array(
                         'name' => 'classictheme_cover', 
                         'value' => 0,
                         'user_guid' => $this->user->guid,
                         'plugin_id' => 'classic-theme' 
); 
  if($this->isCoverSet($this->iscoversettings)){
  return true;	
  }
return false;
}
/**
* Check if user have cover or not;
* @access system
* @return return;
*/
public static function isCover($user){
if(elgg_get_plugin_user_setting(
							'classictheme_cover', 
							 $user, 
							 'classic-theme') == 1){
	  return true;
} 
else {
  return false;	
}

}
/**
* Get cover url;
* @access system
* @return url;
*/
public static function coverUrl($user){	
return  elgg_get_site_url()."mod/classic-theme/cover.php?user={$user}";	
}
/**
* User Profile Cover Management;
* @access system
* @return return;
*/
public function upload_cover($user){	
if(!empty($user)){
   $this->user = $user;	
   $this->OhYesCover = $this->user->getObjects("ClassicThemeCover", 1, 0); 
	if(!$this->OhYesCover){
			$this->OhYesCover = new ElggObject();
			$this->OhYesCover->subtype = "ClassicThemeCover";
			$this->OhYesCover->access_id = 2;
			$this->OhYesCover->save();
			$this->OhYesCover = $this->user->getObjects("ClassicThemeCover", 1, 0); 
	} 
	$this->iscoversettings = array(
                         'name' => 'classictheme_cover', 
                         'value' => 1,
                         'user_guid' => $this->user->guid,
                         'plugin_id' => 'classic-theme' 
                    );
	$this->OhYesCover = $this->OhYesCover[0];
	$this->cover_file = get_uploaded_file('ohyes_cover');		
	if(substr_count($_FILES['ohyes_cover']['type'], 'image/') 
	                   && isset($_FILES['ohyes_cover']) 
					   && $_FILES['ohyes_cover']['error'] == 0){
					$this->filename = "classictheme_cover.jpg";					
					$cover = new ElggFile();
					$cover->setFilename($this->filename);
					$cover->open("write");
					$cover->write($this->cover_file);
					$cover->close();
                    $this->isCoverSet($this->iscoversettings);
          return true;			
				
	}
  }
  return false;
}

}